---
config:
  theme: redux-color
---
mindmap
{{**Paradigmas de Producción**}}
  (**Personalización masiva**)
    *Personalización*
    ::icon(fas fa-arrow-circle-up)
    *Coste*
    ::icon(fas fa-arrow-circle-down)
    *Eficiencia*
    ::icon(fas fa-arrow-circle-up)
  (**Producción en masa**)
    *Personalización*
    ::icon(fas fa-arrow-circle-down)
    *Coste*
    ::icon(fas fa-arrow-circle-down)
    *Eficiencia*
    ::icon(fas fa-arrow-circle-up)
  (**Artesanía**)
    *Eficiencia*
    ::icon(fas fa-arrow-circle-down)
    *Personalización*
    ::icon(fas fa-arrow-circle-up)
    *Coste*
    ::icon(fas fa-arrow-circle-up)
